### ISSUE TITLE
Add phone validation on the register page

### ISSUE THREAD

**Issue by Codehackerone** [DSCKGEC/Libraryly#10]
Phone number validation in `register.ejs` page on the `views` folder is already present. What you have to do is check whether the number is already present in the MongoDB database under the `users` schema.
A similar thing has been implemented for email and username.
For Example, the  `apiEmail` function in `user.controller.js` checks whether the email is present in the database or not by calling the`apiEmail` function in `user.service.js`.
<img width="484" alt="apiEmail" src="https://user-images.githubusercontent.com/64341057/115151097-0a609e80-a089-11eb-92f7-6677973b6542.png">
Now, an ajax call has been made to the `users/api/email/[email_address]` route containing the `apiEmail` function in `user.controller.js`. 
<img width="552" alt="" src="https://user-images.githubusercontent.com/64341057/115151562-ffa70900-a08a-11eb-82c6-92d6434266b6.png">

**Comment by saggy2001** [comment]
Please assign me this issue I will resolve it
