### ISSUE TITLE
Theme suggestions for the website

### ISSUE THREAD

**Issue by singhayushh** [DSCKGEC/Libraryly#16]
Use this issue as a thread for theme suggestions.

The website is to have a dashboard as well as a book catalogue. Share any dribbble shots or pictures or links to website designs that you'd want to suggest!

**Comment by singhayushh** [comment]
For the catalogue of books:
- https://dribbble.com/shots/14913349-Orders-page-IoT-software

Admin dashboard / user and book issue list
- https://dribbble.com/shots/6228132-Daily-UI-03-Dashboard-Group-details
-

**Comment by saggy2001** [comment]
Admin dashboard :

- https://preschool.dreamguystech.com/html-template/index.html?

**Comment by singhayushh** [comment]
Since the theme has been finalized, closing this issue for now. In case you have more suggestions, feel free to communicate over discord, GitHub Discussions or by creating a new issue.
