### ISSUE TITLE
Changing the category in book schema to array of category_id s

### ISSUE THREAD

**Issue by Codehackerone** [DSCKGEC/Libraryly#25]
<img width="434" alt="Screenshot 2021-05-15 at 6 46 38 PM" src="https://user-images.githubusercontent.com/64341057/118362642-eae86300-b5ad-11eb-8168-cc5c44c97eaa.png">

Right now, our bookSchema has the option of accepting only one category. However, a book can have multiple genres, so the category must be changed to an array that will consist of category ids.

**Comment by HaoTruong** [comment]
Hi, This is my first time working on open source, I changed book models category to this:
<img width="543" alt="bookCategory" src="https://user-images.githubusercontent.com/31996968/118407834-86caab00-b650-11eb-8f3d-9e380fcd2f07.png">
Please let me know if it looks good.

**Comment by Codehackerone** [comment]
Yeah, this will solve the issue. Now you can do a PR linked with the issue. 
Also, thank you for contributing to our repo.
Regards.
