### ISSUE TITLE
Creation of Add Book form

### ISSUE THREAD

**Issue by Codehackerone** [DSCKGEC/Libraryly#26]
The post route for the addition of the book is `/books/add`. The page must contain the following form fields. 
- category_id
- title
- ISBN
- price
- pages
- description
- author
- publisher
- inventory
Styling the page is optional. 
The category_id can be multiple or single id.

**Comment by AmitSamui** [comment]
Please assign me this issue . I will work on it

**Comment by Codehackerone** [comment]
Sure, go ahead.

**Comment by AmitSamui** [comment]
Thankyou very much.

**Comment by Rajarshi12321** [comment]
I am interested in this issue. Can you provide a reference?

**Comment by Codehackerone** [comment]
You just have to make a form that contains the fields mentioned above. Backend routes are already made for you

**Comment by Rajarshi12321** [comment]
I have made this form
![image](https://user-images.githubusercontent.com/94736350/183062960-ed13d077-3e4e-420d-8706-726215c686d3.png)

**Comment by Rajarshi12321** [comment]
Updated it a little bit
![image](https://user-images.githubusercontent.com/94736350/183072408-11799d70-7b60-490d-8cd1-11b97988c571.png)

**Comment by Codehackerone** [comment]
Follow the color scheme which is in the login form

**Comment by Rajarshi12321** [comment]
Does this work?
![image](https://user-images.githubusercontent.com/94736350/183132242-53991657-a4cd-458c-b29b-f07fcc7fc1bd.png)

**Comment by Codehackerone** [comment]
Change the font, and color/shape of thd button

**Comment by Rajarshi12321** [comment]
![image](https://user-images.githubusercontent.com/94736350/183136780-a4df2f4a-6083-485f-936f-8cde4843b11e.png)

**Comment by Codehackerone** [comment]
The font again. Use the same font as in login/register

**Comment by Rajarshi12321** [comment]
![image](https://user-images.githubusercontent.com/94736350/183139157-19d73fe7-5198-43f8-8b86-4041589b5e3c.png)

**Comment by Codehackerone** [comment]
Okay. Make a PR

**Comment by Rajarshi12321** [comment]
ok
