### ISSUE TITLE
Navigation bars - top nav and side nav needed

### ISSUE THREAD

**Issue by singhayushh** [DSCKGEC/Libraryly#36]
As discussed in the previous meet, we've divided the website into several components that'll be worked upon separately. This issue covers the navigation component.

For inspiration, you can refer to [this dribbble shot](https://dribbble.com/shots/14913349-Orders-page-IoT-software/attachments/6627675?mode=media). The hex codes and other styling attributes are there in the project readme. Make sure you follow those while designing. And of course, it is to be responsive!

**Comment by Rajarshi12321** [comment]
Hi @singhayushh  bhaiya. I want to work on this issue

**Comment by Codehackerone** [comment]
Sure

**Comment by Rajarshi12321** [comment]
I have made just the structure for now, Can you please suggest me the color theme I should follow, I checked the website but I didn't get a proper idea on the color theme.
And What type of options should I put in the side-nav?
![image](https://user-images.githubusercontent.com/94736350/182434022-ed33a172-7bd3-492f-88b6-f48c5689cfb4.png)

**Comment by Rajarshi12321** [comment]
I have made the proper structure with responsiveness.
I have shown the text area just for the reference as how the navbars are working.

I just need to change the color theme. @singhayushh and @Codehackerone please take a look.
And please guide me about the color theme.

For website:-

https://user-images.githubusercontent.com/94736350/182576760-908261ae-6c50-4a7b-b1ed-a72e3a6638d6.mp4

For Mobile:-


https://user-images.githubusercontent.com/94736350/182577025-c45263f2-b08e-4641-b8ec-b44a5c4f9da8.mp4

**Comment by Rajarshi12321** [comment]
See I have made some changes in color , options in navbar and also added the logo.
Should I make the pull request.

https://user-images.githubusercontent.com/94736350/182797391-ac5cfaaf-4a91-48ec-ac5f-e73cd7bc7890.mp4


https://user-images.githubusercontent.com/94736350/182798337-ff2858a6-805f-4c53-8b0a-a5a12c61c3d5.mp4

**Comment by Codehackerone** [comment]
Follow the color scheme of the login page and make spelling of the project is correct

**Comment by Rajarshi12321** [comment]
Please review these.

https://user-images.githubusercontent.com/94736350/183133691-a4b2cc74-542c-4182-b50c-585b5eacdf1d.mp4


https://user-images.githubusercontent.com/94736350/183133786-49276e7e-3676-4afc-80d8-16bd907e1bb8.mp4

**Comment by Codehackerone** [comment]
- Remove the logo
 - See if you can display the actual username using ejs

**Comment by Rajarshi12321** [comment]
I have removed the logo. But I am unable to fetch the actual username.
Should I make the pull request?

![image](https://user-images.githubusercontent.com/94736350/183244572-30c8bfec-9523-4a65-98f2-fe3e1748ad38.png)

**Comment by Codehackerone** [comment]
Okay.
