### ISSUE TITLE
Footer Component needed

### ISSUE THREAD

**Issue by singhayushh** [DSCKGEC/Libraryly#37]
As discussed in the previous meet, we've divided the website into several components that'll be worked upon separately. This issue covers the footer component.

Add the footer inside the `views/partials` directory, where you'll also find the header component. The footer is to contain a colophon section on the left side and a list of links on the right. For the time being, you can have store dummy data for these sections, we'll look into that later on.

The hex codes and other styling attributes are there in the project readme. Make sure you follow those while designing.

**Comment by deepaahuja92** [comment]
Hello!I am  Deepa Ahuja.I know HTML,CSS and JS.I want to work on this issue please assign this issue to me.

**Comment by singhayushh** [comment]
Hello @deepaahuja92 
Thanks for showing your interests in contributing to this issue but someone else is already working on this. 

We have a discord server for the community [here](https://dsck.ml/discord). These issues had been discussed and assigned over discord 😅. So if you're interested in working on some other issue, you can hop into our discord and interact with other members.

**Comment by Gauravmitra-hash** [comment]
Could you please assign me this task? @singhayushh
