### ISSUE TITLE
Changes required in readme 

### ISSUE THREAD

**Issue by singhayushh** [DSCKGEC/Libraryly#4]
There are two changes currently needed in the readme.md file of the project
- fixing typos
- to the project structure section, add another directory to the tree named `middlewares`. 

For the second point above, kindly create a directory under the name `middlewares` in the root directory of the project and add an empty file named `auth.middleware.js` in this newly created directory and push all changes.

**Comment by agnisain123** [comment]
Can I fix the typos?

**Comment by singhayushh** [comment]
@agnisain123 go for both.
