### ISSUE TITLE
SVG Animations for the landing page. 

### ISSUE THREAD

**Issue by singhayushh** [DSCKGEC/Libraryly#40]
We are looking for contributions towards svg animations to be used in the landing page of the website. 

Since we are making a website on library management, svgs about books, reading and library management are preferred. Make sure you use open sourced SVGs and vectors, maybe from [undraw.co](https://undraw.co) 

Best of luck and thanks in advance!

**Comment by AmitSamui** [comment]
Assign  me this issue.
