### ISSUE TITLE
Creation of Add Book form

### ISSUE THREAD

**Issue by Codehackerone** [DSCKGEC/Libraryly#42]
The post route for the addition of a category is `/category/add`
The form should have the following fields.
- name (Name of the category/genre)
- desc (Small description of the category)

**Comment by singhayushh** [comment]
This is a duplicate issue.
Checkout #26

**Comment by singhayushh** [comment]
Once the form component is created by Amit, who is assigned issue 26, we will be using the same code as snippet and create other forms that are needed. So, separate issues isn't needed for each of the form page as we do not want to have multiple form templates with different code and styling.
