### ISSUE TITLE
Add favicon to all the webpages

### ISSUE THREAD

**Issue by Codehackerone** [DSCKGEC/Libraryly#9]
We need a favicon for the website.
 Contributions are welcome!
The image to be used is located at `views/img/logo_small.png`

**Comment by priyalHedau15** [comment]
hey , can u assign this issue to me

**Comment by Codehackerone** [comment]
Yes, sure. Feel free to comment if you have any doubts.

**Comment by priyalHedau15** [comment]
Yaa sure .👍
